### ISSUE TITLE
Tracking Metrics

### ISSUE THREAD

**Issue by EnriqueCorado** [benetech/ServiceNet#1555]
User Story (encompasses persona, purpose, value) - e.g. As a [persona] i want to be able to [purpose] so that I can [value]:

As a Benetech Admin, I want to be able to track metrics in order to have data to report and especially during the pilot with CA Marin, see which areas we can potentially improve on

Description:

Need to be tracking:
- referrals (we are)
- Referrals should get flagged when referrals are made to CBOs which have not been claimed (in database) 
- or which have incomplete information (These are potential targets for our outreach efforts to get CBOs signed up to use the platform.)
**related tasks to above #1487 & 1541**

Separately: need to track metrics such as per user (add a new table for each user in order to track usage?)
- search terms 
- frequency of usage
- time per usage 
- number of referrals 
- number of people checked in 
- places person refers to 
- updates to record (fields and the text change)

Scope (includes UI mockups, user flow, and out of scope):

dev please advice is these metrics should be tracked on a separate table per user 

Acceptance criteria (includes edge cases):
*

Dependencies (links to other related tasks):
*

Any required analytics for task:
*

Dev Signoffs
- [ ] Unit test added for the core business features at the minimum
- [ ] Code review passed
- [ ] CI passed successfully
- [ ] CodeQL scan for vulnerabilities in code has passed 
- [ ] Docker images have been built and deployed to the dev server

QA Signoffs
- [ ] Passes Acceptance Criteria
- [ ] All bug reports fixed/merged/tested
- [ ] Regression test cases cycle updated if needed

Product Signoff
- [ ] Approved for release
